addSbtPlugin("com.github.gseitz"        %   "sbt-release"                 % "1.0.7")
addSbtPlugin("com.jsuereth"             %   "sbt-pgp"                     % "1.1.2")
addSbtPlugin("org.xerial.sbt"           %   "sbt-sonatype"                % "2.0")
addSbtPlugin("org.scoverage"            %   "sbt-scoverage"               % "1.5.1")
addSbtPlugin("org.scoverage"            %   "sbt-coveralls"               % "1.2.2")
addSbtPlugin("org.scalastyle"           %%  "scalastyle-sbt-plugin"       % "1.0.0")
addSbtPlugin("com.lucidchart"           %   "sbt-scalafmt"                % "1.15")
addSbtPlugin("ch.epfl.scala"            %%  "sbt-scalafix"                % "0.6.0-M12")
