addSbtPlugin("com.github.gseitz"        %   "sbt-release"                 % "1.0.11")
addSbtPlugin("com.jsuereth"             %   "sbt-pgp"                     % "2.0.0")
addSbtPlugin("org.xerial.sbt"           %   "sbt-sonatype"                % "2.5")
addSbtPlugin("org.scalastyle"           %%  "scalastyle-sbt-plugin"       % "1.0.0")
addSbtPlugin("com.lucidchart"           %   "sbt-scalafmt"                % "1.15")
addSbtPlugin("ch.epfl.scala"            %%  "sbt-scalafix"                % "0.9.24")
