name: snyk monitor 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/scala@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        SNYK_ORG: ${{ secrets.SNYK_ORG }}
      with:
        args: --org=$SNYK_ORG --project-name=guardian/tip
        command: monitor  
